// Single source of truth for IPC channel names shared by main, preload, and renderer.
// Command channels: ipcMain.handle <-> ipcRenderer.invoke (request/response).
// Stream channels: ipcMain pushes events keyed by a correlation id; renderer subscribes via ipcRenderer.on.

export const IPC = {
  appVersion: 'app:version',
  sbxHealth: 'sbx:health',
  sbxLs: 'sbx:ls',
  sbxCreate: 'sbx:create',
  sbxStop: 'sbx:stop',
  sbxStart: 'sbx:start',
  sbxRm: 'sbx:rm',
  sbxPortsList: 'sbx:ports:list',
  sbxPortsPublish: 'sbx:ports:publish',
  sbxPortsUnpublish: 'sbx:ports:unpublish',
  sbxKitInspect: 'sbx:kit:inspect',
  sbxKitValidate: 'sbx:kit:validate',
  sbxKitAdd: 'sbx:kit:add',
  kitLibraryList: 'kitLibrary:list',
  kitLibraryRecordUsage: 'kitLibrary:recordUsage',
  kitLibraryRemove: 'kitLibrary:remove',
  sbxPolicyList: 'sbx:policy:list',
  sbxPolicyAllowNetwork: 'sbx:policy:allowNetwork',
  sbxPolicyDenyNetwork: 'sbx:policy:denyNetwork',
  sbxPolicyRemoveNetwork: 'sbx:policy:removeNetwork',
  sbxPolicyLog: 'sbx:policy:log',
  sbxPolicyInit: 'sbx:policy:init',
  sbxPolicyReset: 'sbx:policy:reset',
  sbxMcpList: 'sbx:mcp:list',
  sbxMcpInspect: 'sbx:mcp:inspect',
  sbxMcpAdd: 'sbx:mcp:add',
  sbxMcpAuth: 'sbx:mcp:auth',
  sbxMcpAuthStatus: 'sbx:mcp:authStatus',
  sbxMcpAuthRemove: 'sbx:mcp:authRemove',
  sbxMcpRemove: 'sbx:mcp:remove',
  sbxMcpLoad: 'sbx:mcp:load',
  sbxSecretList: 'sbx:secret:list',
  sbxSecretSet: 'sbx:secret:set',
  sbxSecretSetOAuth: 'sbx:secret:setOAuth',
  sbxSecretSetFromPasswordManager: 'sbx:secret:setFromPasswordManager',
  sbxSecretRemove: 'sbx:secret:remove',
  sbxPasswordManagerList: 'sbx:passwordManager:list',
  sbxDaemonStart: 'sbx:daemon:start',
  sbxDaemonStop: 'sbx:daemon:stop',
  sbxDaemonRestart: 'sbx:daemon:restart',
  sbxDiagnose: 'sbx:diagnose',
  logsExport: 'logs:export',
  dialogPickFolder: 'dialog:pickFolder',
  dialogPickKitReference: 'dialog:pickKitReference',
  chatStart: 'chat:start',
  chatSendMessage: 'chat:sendMessage',
  chatStop: 'chat:stop',
  chatEvent: 'chat:event',
  chatLoginClaude: 'chat:loginClaude',
  terminalStart: 'terminal:start',
  terminalInput: 'terminal:input',
  terminalResize: 'terminal:resize',
  terminalStop: 'terminal:stop',
  terminalData: 'terminal:data',
  settingsGetDefaultView: 'settings:getDefaultView',
  settingsSetDefaultView: 'settings:setDefaultView',
  settingsGetDefaultPermissionMode: 'settings:getDefaultPermissionMode',
  settingsSetDefaultPermissionMode: 'settings:setDefaultPermissionMode',
  settingsGetLastAppliedPolicyTier: 'settings:getLastAppliedPolicyTier',
  sbxLogin: 'sbx:login',
  sbxLogout: 'sbx:logout',
  shellOpenExternal: 'shell:openExternal'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
